### ISSUE TITLE
FPTR_RT_CASH_OUT - Receipt method is not supported

### ISSUE THREAD

**Issue by mifkamaz** [shtrih-m/javapos_shtrih#10]
Опишу сразу 2 проблемы
1. При печати внесения затем выплаты, оба раза печатаются выплаты
2. Если сразу после подключения распечатать выплату происходит ошибка

**Алгоритм воспроизведения:**
1. Подключаемся к кассе
2. Снимаем Z-отчет
3. Открываем смену
4. Печатаем внесение (FPTR_RT_CASH_IN)
5. **Печатаем выплату (FPTR_RT_CASH_OUT)**
6. **Вместо выплаты печатается внесение**
7. Переподключаемся к кассе
8. **Печатаем выплату (FPTR_RT_CASH_OUT)**
9. **Происходит ошибка**
10. Снимаем Z-отчет. В нем написанно ВНЕСЕНИЙ: 2, ВЫПЛАТ: 0

Используемое оборудование **ШТРИХ-MOBILE-Ф**
Печать внесения
```
        printer.resetPrinter();
        printer.setFiscalReceiptType(FiscalPrinterConst.FPTR_RT_CASH_IN);
        printer.beginFiscalReceipt(true);
        printer.printRecCash(toCents(amount));
        printer.printRecTotal(0, toCents(amount), "0");
        printer.endFiscalReceipt(true);
```
Печать выплаты
```
        printer.resetPrinter();
        printer.beginFiscalReceipt(true);
        printer.setFiscalReceiptType(FiscalPrinterConst.FPTR_RT_CASH_OUT);
        printer.printRecCash(toCents(amount));
        printer.printRecTotal(0, toCents(amount), "0");
        printer.endFiscalReceipt(true);
```
Стектрейс
```
   jpos.JposException: Receipt method is not supported
       at com.shtrih.jpos.fiscalprinter.receipt.CustomReceipt.notSupported(CustomReceipt.java:87)
       at com.shtrih.jpos.fiscalprinter.receipt.CustomReceipt.printRecCash(CustomReceipt.java:142)
       at com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl.printRecCashAsync(FiscalPrinterImpl.java:3765)
       at com.shtrih.jpos.fiscalprinter.request.PrintRecCashRequest.execute(PrintRecCashRequest.java:22)
       at com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl.execute(FiscalPrinterImpl.java:746)
       at com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl.printRecCash(FiscalPrinterImpl.java:3770)
       at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.printRecCash(FiscalPrinterService.java:2519)
       at jpos.FiscalPrinter.printRecCash(FiscalPrinter.java:4831)
       at com.shtrih.fiscalprinter.ShtrihFiscalPrinter113.printRecCash(ShtrihFiscalPrinter113.java:273))
```

**Comment by nyxiscoo1** [comment]
1. Все дело в коде, выбор типа чека происходит при вызове метода printer.beginFiscalReceipt(true);, при печати выплаты сразу же после внесения тип чека остается от предыдущего установленного значения - FiscalPrinterConst.FPTR_RT_CASH_IN.
Вот код печатающий 2 чека подряд: внесение и затем выплату:
```
            printer.resetPrinter();
            printer.setFiscalReceiptType(FiscalPrinterConst.FPTR_RT_CASH_IN);
            printer.beginFiscalReceipt(true);
            printer.printRecCash(123);
            printer.printRecTotal(0,123, "0");
            printer.endFiscalReceipt(true);

            printer.resetPrinter();
            printer.setFiscalReceiptType(FiscalPrinterConst.FPTR_RT_CASH_OUT);
            printer.beginFiscalReceipt(true);
            printer.printRecCash(122);
            printer.printRecTotal(0, 122, "0");
            printer.endFiscalReceipt(true);
```

2. У меня вышеописанный код выплаты выполняется нормально в том числе и сразу после подключения, как минимум на текущей версии 411.
