### ISSUE TITLE
mcClearBuffer выдаёт ошибку

### ISSUE THREAD

**Issue by Tango600** [shtrih-m/javapos_shtrih#156]
Касса: Штрих-Нано-Ф, прошивка версии 355.
Драйвер версии: 679.
При вызове mcClearBuffer происходит исключение.
errorCode=114, extended=461.
сообщение=161, FS: Invalid 0xBx command sequence.

**Comment by VitalyKravtsov2016** [comment]
Судя по всему, Штрих-Нано-Ф не поддерживает очистку буфера кодов маркировки. 
В ФР Сергея Ляховича это работает. Попрошу разработчика ФР поправить.

**Comment by Tango600** [comment]
А как быть с проверкой кода, точнее с получением результат проверки?

**Comment by Tango600** [comment]
> Судя по всему, Штрих-Нано-Ф не поддерживает очистку буфера кодов маркировки. В ФР Сергея Ляховича это работает. Попрошу разработчика ФР поправить.

Пока рабочим способом является только чтение документа из кассы и выявлением тега 2106.

**Comment by VitalyKravtsov2016** [comment]
Для проверки кода маркировки нужно использовать команду FF61. 
В драйвере это код команды directIO SMFPTR_DIO_CHECK_ITEM_CODE2.
В ответе возвращается значение тега 2106.

**Comment by Tango600** [comment]
F v

> Для проверки кода маркировки нужно использовать команду FF61. В драйвере это код команды directIO SMFPTR_DIO_CHECK_ITEM_CODE2. В ответе возвращается значение тега 2106.

А какой это метод драйвера?

**Comment by VitalyKravtsov2016** [comment]
Это метод directIO(SMFPTR_DIO_CHECK_ITEM_CODE2).
Реализация метода:
    public void execute(int[] data, Object object) throws Exception {

        Object[] params = (Object[])object;
        DIOUtils.checkObjectMinLength(params, 10);
        
        FSCheckMC command = new FSCheckMC();
        command.itemStatus = (Integer)params[0];
        command.checkMode = (Integer)params[1];
        command.mcData = (byte[])params[2];
        command.tlv = (byte[])params[3];
        getPrinter().check(getPrinter().fsCheckMC(command));
        params[4] = new Integer(command.localCheckStatus);
        params[5] = new Integer(command.localErrorCode);
        params[6] = new Integer(command.symbolicType);
        params[7] = new Integer(command.serverErrorCode);
        params[8] = new Integer(command.serverCheckStatus);
        params[9] = command.serverTLVData;
    }

Сейчас добавлю в класс ShtrihFiscalPrinter113

**Comment by Tango600** [comment]
Кроме не ещё реализованного в версии 633, метода, другие аналогичные или какая то комбинация методов не работают?
ККМ: Штрих-Нано-Ф.

**Comment by VitalyKravtsov2016** [comment]
Метод реализован давно. Просто здесь я проиллюстрировал реализацию.

**Comment by VitalyKravtsov2016** [comment]
Класс ShtrihFiscalPrinter113 упрощает вызов команд directIO

**Comment by VitalyKravtsov2016** [comment]
https://github.com/shtrih-m/javapos_shtrih/releases/tag/687

    public class CheckItemCodeResponse
    {
        public int localCheckStatus;
        public int localErrorCode;
        public int symbolicType;
        public int serverErrorCode;
        public int serverCheckStatus;
        public byte[] serverTLVData;
    
        public CheckItemCodeResponse(){
        }
    }
    
    public CheckItemCodeResponse checkItemCode2(int itemStatus, 
            int checkMode, byte[] data, byte[] tlv) throws Exception{

        Object[] params = new Object[10];
        
        params[0] = new Integer(itemStatus);
        params[1] = new Integer(checkMode);
        params[2] = data;
        params[3] = tlv;
        directIO(SmFptrConst.SMFPTR_DIO_CHECK_ITEM_CODE2, null, params);
        CheckItemCodeResponse response = new CheckItemCodeResponse();
        response.localCheckStatus = (Integer)params[4];
        response.localErrorCode = (Integer)params[5];
        response.symbolicType = (Integer)params[6];
        response.serverErrorCode = (Integer)params[7];
        response.serverCheckStatus = (Integer)params[8];
        response.serverTLVData = (byte[])params[9];
        return response;
    }

**Comment by Tango600** [comment]
> Для проверки кода маркировки нужно использовать команду FF61. В драйвере это код команды directIO SMFPTR_DIO_CHECK_ITEM_CODE2. В ответе возвращается значение тега 2106.
Нет.
public static final int SMFPTR_DIO_SEND_ITEM_CODE = 0x61;

**Comment by Tango600** [comment]
Вызов _checkItemCode2(1, 0, codeRawData, new byte[0])_ приводит к невозможности закрыть чек.
Вызов _checkItemCode2(1, 0, codeRawData, **null**)_ к ошибке, разрыву соединения.

**Comment by Tango600** [comment]
Провёл на драйвере 692, чеки закрываются, соединение не рвётся.

**Comment by VitalyKravtsov2016** [comment]
А что с повторным соединением?

**Comment by Tango600** [comment]
У меня таких проблем не поступало, подхватывает сразу. Посмотрим через неделю, как разойдётся приложение по сети.

**Comment by vk-gc** [comment]
Имеется следующая последовательность вызова методов для регистрации позиции в чеке согласно примеру из `FFD105Documents`:

```
fsWriteOperationTag(2108, 0)
setParameter(SmFptrConst.SMFPTR_DIO_PARAM_ITEM_PAYMENT_TYPE, 4)
setParameter(SmFptrConst.SMFPTR_DIO_PARAM_ITEM_SUBJECT_TYPE, 33)
setParameter(SmFptrConst.SMFPTR_DIO_PARAM_ITEM_TOTAL_AMOUNT, 100)
printRecItem(...)
```

В  какой момент необходимо вызывать `checkItemCode2`, `setItemCode`, `acceptItemCode(true)` и какая должна быть последовательность вызова, чтобы печаталось [M+/-]?

И еще вопрос, у атола есть таймаут на серверную проверку КМ, есть ли для штриха такая опция?

**Comment by Tango600** [comment]
У меня лучше всего работала такая последовательность. Но, результат проверки я ловил уже разбирая сам чек, после проведения.
'''java
printer.setItemCode(goodCheckInfo.codeMarking);
printer.checkItemCode(goodCheckInfo.codeMarking);
'''

**Comment by vk-gc** [comment]
> У меня лучше всего работала такая последовательность. Но, результат проверки я ловил уже разбирая сам чек, после проведения.
> 
> ```java
> printer.setItemCode(goodCheckInfo.codeMarking);
> printer.checkItemCode(goodCheckInfo.codeMarking);
> ```

Вызываете просто `checkItemCode(code)` без передачи планируемого статуса и без меры и дробной части для весовой молочки?

И тайматы никак не ставятся?

**Comment by Tango600** [comment]
Параметры  передаю ранее. Про таймауты не знаю.

**Comment by VitalyKravtsov2016** [comment]
Добрый день. 
Таймауты проверки КМ задаются в таблице ФР 19, Параметры офд:
19,1,7,2,0,5,65535,'Таймаут чтения ответа км','33'
19,1,8,2,0,2,65535,'Таймаут чтения ответа км при проверке','5'

**Comment by vk-gc** [comment]
Иногда (не каждый раз), происходит падение на проверке кода маркировки методом `checkItemCode2`.

Планшет подключен к кассе через wi-fi, касса Штрих Нано.

Лог падения:

```
E/[AGC_LOG]AGConnectCrashHandler: is handling exception
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.goodscontrol.terminal, PID: 24257
    jpos.JposException: Connection closed
        at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.getJposExceptionWithoutDetails(JposExceptionHandler.java:94)
        at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.getJposException(JposExceptionHandler.java:54)
        at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.handleException(JposExceptionHandler.java:44)
        at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.handleException(FiscalPrinterService.java:40)
        at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.directIO(FiscalPrinterService.java:269)
        at jpos.BaseJposControl.directIO(BaseJposControl.java:461)
        at com.shtrih.fiscalprinter.ShtrihFiscalPrinter113.directIO(ShtrihFiscalPrinter113.java:1023)
        at com.shtrih.fiscalprinter.ShtrihFiscalPrinter113.checkItemCode2(ShtrihFiscalPrinter113.java:2521)
        at ru.goodscontrol.pos.shtrih.fptr.Fptr_CheckMarkingCodeKt.utilCheckMarkingCode(Fptr+CheckMarkingCode.kt:69)
```

Падение происходит только при подключении через wi-fi. по BLE такого не происходит, но и по BLE касса не ходит в интернет проверять код. По USB совсем не подключается. 

Версия драйвера 699

**Comment by Tango600** [comment]
Что даёт команда _checkItemCode2_ на МГМ-ФН?
У меня получается вот что:
![Проверка КМ Штрих](https://github.com/shtrih-m/javapos_shtrih/assets/5998520/0a2abf90-b0b6-4edd-9c85-29b6b1a72173)
Что значит поле _localErrorCode_, оно не 0.

**Comment by vk-gc** [comment]
@Tango600 Вот в исходниках нашел:

<img width="906" alt="Screenshot 2023-07-24 at 18 14 32" src="https://github.com/shtrih-m/javapos_shtrih/assets/110912164/0c219b61-0ba1-4816-ae69-234591fb9936">
