### ISSUE TITLE
Документы не отправляются в ОФД

### ISSUE THREAD

**Issue by vladislav-larionov** [shtrih-m/javapos_shtrih#165]
На продуктовые ФР мобайл штрих появились жалобы на ошибку `20, ФН: Исчерпан ресурс хранения`. При подключении устройства к ПК, документы отправляются нормально.
В логах достаточно часто появляется ошибка `FDO data sending failed` с двумя разными выводами.
Первый:
```java
30.06.2023 10:28:14.753 [Thread-970] c.s.f.SMFiscalPrinterImpl - testOFDConnection: OK
30.06.2023 10:28:14.754 [Thread-970] c.s.f.SMFiscalPrinterImpl - FF30h, Fiscal storage: read buffer status
30.06.2023 10:28:14.758 [Thread-970] c.s.jpos.fiscalprinter.FDOService - FDO data sending failed
java.lang.InterruptedException: null
	at com.shtrih.fiscalprinter.SMFiscalPrinterImpl.deviceExecute(SMFiscalPrinterImpl.java:238) ~[na:0.0]
	at com.shtrih.fiscalprinter.SMFiscalPrinterImpl.executeCommand(SMFiscalPrinterImpl.java:460) ~[na:0.0]
	at com.shtrih.fiscalprinter.SMFiscalPrinterImpl.execute(SMFiscalPrinterImpl.java:425) ~[na:0.0]
	at com.shtrih.fiscalprinter.SMFiscalPrinterImpl.fsReadBufferStatus(SMFiscalPrinterImpl.java:3647) ~[na:0.0]
	at com.shtrih.fiscalprinter.SMFiscalPrinterImpl.fsReadBlockData(SMFiscalPrinterImpl.java:4045) ~[na:0.0]
	at com.shtrih.fiscalprinter.SMFiscalPrinterImpl.sendFDODocuments(SMFiscalPrinterImpl.java:5286) ~[na:0.0]
	at com.shtrih.jpos.fiscalprinter.FDOService.run(FDOService.java:64) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:831) ~[na:0.0]
30.06.2023 10:28:14.760 [Thread-970] c.s.jpos.fiscalprinter.FDOService - FSService stopped
```

Второй:
```java
30.06.2023 10:28:35.154 [Thread-974] c.s.jpos.fiscalprinter.FDOService - FDO data sending failed
com.shtrih.fiscalprinter.DeviceException: Socket is closed
	at com.shtrih.fiscalprinter.SMFiscalPrinterImpl.sendFDOData(SMFiscalPrinterImpl.java:5358) ~[na:0.0]
	at com.shtrih.fiscalprinter.SMFiscalPrinterImpl.sendFDODocuments(SMFiscalPrinterImpl.java:5302) ~[na:0.0]
	at com.shtrih.jpos.fiscalprinter.FDOService.run(FDOService.java:64) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:831) ~[na:0.0]
30.06.2023 10:28:35.155 [Thread-974] c.s.jpos.fiscalprinter.FDOService - FSService stopped
```

Версия драйвера 696. [Лог с production](https://github.com/shtrih-m/javapos_shtrih/files/11975409/shtrih_production.log). [Лог с тестового ккт](https://github.com/shtrih-m/javapos_shtrih/files/11975408/shtrih_test1.txt).

На актуальной версии драйвера 699 проблема тоже есть, хотя тестировали пока только на тестовом ккт. [Лог](https://github.com/shtrih-m/javapos_shtrih/files/11975407/shtrih_test2.log).
Вы не могли бы посмотреть в чём дело? Или может быть проблема уже поправлена в 699?

**Comment by VitalyKravtsov2016** [comment]
Добрый день. Да, в последней версии драйвера ошибка исправлена.
