### ISSUE TITLE
Чек коррекции

### ISSUE THREAD

**Issue by mifkamaz** [shtrih-m/javapos_shtrih#29]
Как правильно сделать чек коррекции?

Делаю так

`printer.fsPrintCorrectionReceipt(0, 1_000_00);`

Ошибка

```
Caused by: com.shtrih.fiscalprinter.SmFiscalPrinterException: 1, ФН: Неизвестная команда, неверный формат посылки или неизвестные параметры
     at com.shtrih.fiscalprinter.SMFiscalPrinterImpl.check(SMFiscalPrinterImpl.java:223)
     at com.shtrih.jpos.fiscalprinter.directIO.DIOPrintCorrectionReceipt.execute(DIOPrintCorrectionReceipt.java:28)
     at com.shtrih.jpos.fiscalprinter.directIO.DirectIOHandler2.directIO(DirectIOHandler2.java:378)
     at com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl.directIO(FiscalPrinterImpl.java:2064)
     at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.directIO(FiscalPrinterService.java:272)
```

**Comment by nyxiscoo1** [comment]
1. Ошибка возникает из-за первого параметра, т.к. согласно ФФД допустимы 2 значения: 1 - приход, 3 - расход.
2. Есть 2 версии команды печти чека коррекции, v1 представленная выше и v2( fsPrintCorrectionReceipt3) которая позволяет задать большее количество парамтров, рекомендуется использовать v2.

**Comment by nyxiscoo1** [comment]
На самом деле печать чека коррекции не так проста как кажется на первый взгляд, особенно, если это делать для ФФД 1.05, пока не знаю в каком формате лучше создать доку создал страницу на [вики](https://github.com/shtrih-m/javapos_shtrih/wiki).
Для формирования чека коррекции под ФФД 1.05 нужно обновиться на драйвер 469.

**Comment by mifkamaz** [comment]
`fsPrintCorrectionReceipt` - работает корректно

`fsPrintCorrectionReceipt3` - выдает ошибку

```
Caused by: com.shtrih.fiscalprinter.SmFiscalPrinterException: 55, Команда не поддерживается в данной реализации
                                                                             at com.shtrih.fiscalprinter.SMFiscalPrinterImpl.check(SMFiscalPrinterImpl.java:223)
                                                                             at com.shtrih.jpos.fiscalprinter.directIO.DIOPrintCorrectionReceipt2.execute(DIOPrintCorrectionReceipt2.java:45)
                                                                             at com.shtrih.jpos.fiscalprinter.directIO.DirectIOHandler2.directIO(DirectIOHandler2.java:374)
                                                                             at com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl.directIO(FiscalPrinterImpl.java:2064)
                                                                             at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.directIO(FiscalPrinterService.java:272)
                                                                             at jpos.BaseJposControl.directIO(BaseJposControl.java:461) 
                                                                             at com.shtrih.fiscalprinter.ShtrihFiscalPrinter113.directIO(ShtrihFiscalPrinter113.java:1016) 
                                                                             at com.shtrih.fiscalprinter.ShtrihFiscalPrinter113.fsPrintCorrectionReceipt3(ShtrihFiscalPrinter113.java:1667) 
                                                                             at com.bifit.cashdesk.mobile.driver.ShtrihProtocol.correction(ShtrihProtocol.java:757) 
                                                                             at com.bifit.cashdesk.mobile.views.tasks.CorrectionTask.executeCommand(CorrectionTask.java:81) 
                                                                             at com.bifit.cashdesk.mobile.views.tasks.CorrectionTask.executeCommand(CorrectionTask.java:20) 
                                                                             at com.bifit.cashdesk.mobile.views.tasks.AbstractKktTask.execute(AbstractKktTask.java:75) 
                                                                             at com.bifit.cashdesk.mobile.views.tasks.AbstractKktTask.execute(AbstractKktTask.java:21) 
                                                                             at com.bifit.cashdesk.mobile.views.tasks.AbstractTask$1.run(AbstractTask.java:84) 
                                                                             at org.greenrobot.eventbus.util.AsyncExecutor$1.run(AsyncExecutor.java:116) 
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                             at java.lang.Thread.run(Thread.java:818) 
```

Используемая версия протокола `<prop name="protocolType" type="String" value="1"/>`
Используемая версия драйвера `469`

**Comment by nyxiscoo1** [comment]
Видимо версия 20019 или меньше, печать чека коррекции v2 поддерживается начиная с прошивки 20020.
