### ISSUE TITLE
В тестовом приложении не работает связь по USB 

### ISSUE THREAD

**Issue by mifkamaz** [shtrih-m/javapos_shtrih#42]
Устройство ШТРИХ-MOBILE-ПТК
deviceId == 1003
```
jpos.JposException: Нет связи
    at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.getJposExceptionWithoutDetails(JposExceptionHandler.java:90)
    at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.getJposException(JposExceptionHandler.java:52)
    at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.handleException(JposExceptionHandler.java:41)
    at com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl.handleException(FiscalPrinterImpl.java:409)
    at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.handleException(FiscalPrinterService.java:39)
    at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.setDeviceEnabled(FiscalPrinterService.java:139)
    at jpos.BaseJposControl.setDeviceEnabled(BaseJposControl.java:171)
    at com.shtrih.fiscalprinter.ShtrihFiscalPrinter113.setDeviceEnabled(ShtrihFiscalPrinter113.java:969)
    at com.shtrih.tinyjavapostester.MainActivity.connectToUSBDevice(MainActivity.java:1313)
    at java.lang.reflect.Method.invoke(Native Method)
    at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
    at android.view.View.performClick(View.java:5637)
    at android.view.View$PerformClick.run(View.java:22429)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by nyxiscoo1** [comment]
В чем отличие от #15?

**Comment by mifkamaz** [comment]
Подумал что в тестовом приложении все заявленные функции должны работать
