### ISSUE TITLE
ShtrihFiscalPrinter113 readTable writeTable написанны неправильно

### ISSUE THREAD

**Issue by mifkamaz** [shtrih-m/javapos_shtrih#6]
При чтении/записи из таблицы просиходит ошибка 
```
[ShtrihProtocol:getCashiersInfo:117]: Data parameter cannot be null
    jpos.JposException: Data parameter cannot be null
        at com.shtrih.jpos.DIOUtils.checkDataNotNull(DIOUtils.java:31)
        at com.shtrih.jpos.DIOUtils.checkDataMinLength(DIOUtils.java:44)
        at com.shtrih.jpos.fiscalprinter.directIO.DIOWriteTable.execute(DIOWriteTable.java:29)
        at com.shtrih.jpos.fiscalprinter.directIO.DirectIOHandler.directIO(DirectIOHandler.java:113)
        at com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl.directIO(FiscalPrinterImpl.java:2002)
        at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.directIO(FiscalPrinterService.java:272)
        at jpos.BaseJposControl.directIO(BaseJposControl.java:461)
        at com.shtrih.fiscalprinter.ShtrihFiscalPrinter113.directIO(ShtrihFiscalPrinter113.java:1006)
        at com.shtrih.fiscalprinter.ShtrihFiscalPrinter113.writeTable(ShtrihFiscalPrinter113.java:1156)
```
Связанна она с тем что изначально в функции` ShtrihFiscalPrinter113.readTable` и `ShtrihFiscalPrinter113.readTable` параметр `data == null`

Работающая реалищация методов

```
    public String readTable(int tableNumber, int rowNumber, int fieldNumber) throws JposException {
        String[] output = new String[1];
        int[] data = new int[]{tableNumber, rowNumber, fieldNumber};
        this.directIO(5, data, output);
        return output[0];
    }

    public void writeTable(int tableNumber, int rowNumber, int fieldNumber, String fieldValue) throws JposException {
        String[] input = new String[]{fieldValue};
        int[] data = new int[]{tableNumber, rowNumber, fieldNumber};
        this.directIO(6, data, input);
    }
```

**Comment by nyxiscoo1** [comment]
И да и нет. В виду исторически сложившихся обстоятельств есть 2 версии DIO-команд, выбор производится параметром compatibilityLevel = 0/1 в jpos.xml, текущая реализация написана для compatibilityLevel = 0, Ваша реализация верна для версии 1.

Вам нужно в jpos.xml добавить параметр <prop name="compatibilityLevel" type="String" value="0"/>.

**Comment by mifkamaz** [comment]
@nyxiscoo1 
Спасибо, заработало
