### ISSUE TITLE
Ошибка при внесении и инкасации

### ISSUE THREAD

**Issue by mifkamaz** [shtrih-m/javapos_shtrih#7]
При попытке внесения или инкасации
```
        printer.resetPrinter();
        printer.beginFiscalReceipt(true);
        printer.setFiscalReceiptType(FiscalPrinterConst.FPTR_RT_CASH_OUT);
        printer.printRecCash(amount.longValue());
        printer.endFiscalReceipt(true);
```
Возникает ошибка

```
04-18 13:03:19.937 12770-12906/com.bifit.cashdesk.mobile E/AbstractTask: Error
     jpos.JposException: Wrong printer state(com.shtrih.jpos.fiscalprinter.FiscalPrinterState@42726140, "FPTR_PS_FISCAL_RECEIPT"
         at com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl.throwWrongStateError(FiscalPrinterImpl.java:4437)
         at com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl.checkPrinterState(FiscalPrinterImpl.java:3968)
         at com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl.endFiscalReceipt(FiscalPrinterImpl.java:3046)
         at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.endFiscalReceipt(FiscalPrinterService.java:1531)
         at jpos.FiscalPrinter.endFiscalReceipt(FiscalPrinter.java:3817)
```
Что странно, т.к. метод `beginFiscalReceipt` выполняется без ошибок

**Comment by nyxiscoo1** [comment]
Да, дейтсвительно, в тестах написано печатать выплату/внесение таким кодом:
```
printer.setFiscalReceiptType(FPTR_RT_CASH_IN);
printer.beginFiscalReceipt(true);
printer.printRecCash(100000);
printer.printRecTotal(0, 100000, "");
printer.endFiscalReceipt(true);
```
Без строки printRecTotal сейчас работать не будет.
