### ISSUE TITLE
После установки jdk 11 перестали печататься теги

### ISSUE THREAD

**Issue by battleda** [shtrih-m/javapos_shtrih#86]
Добрый день!

После установки jdk 11 на машине перестали добавляться теги:
printer.fsWriteTag(1227, "Усама Бин Ладен");

Трейс:
jpos.JposException: java.nio.CharBuffer.position(I)Ljava/nio/CharBuffer;
	at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.getJposExceptionWithoutDetails(JposExceptionHandler.java:90)
	at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.getJposException(JposExceptionHandler.java:52)
	at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.handleException(JposExceptionHandler.java:41)
	at com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl.handleException(FiscalPrinterImpl.java:457)
	at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.handleException(FiscalPrinterService.java:37)
	at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.directIO(FiscalPrinterService.java:253)
	at jpos.BaseJposControl.directIO(BaseJposControl.java:461)
	at com.shtrih.fiscalprinter.ShtrihFiscalPrinter113.directIO(ShtrihFiscalPrinter113.java:1020)
	at com.shtrih.fiscalprinter.ShtrihFiscalPrinter113.fsWriteTag(ShtrihFiscalPrinter113.java:1918)

**Comment by nyxiscoo1** [comment]
Добрый день! 

Есть ли описание в исключении?

**Comment by battleda** [comment]
Описания нет. 
При переключении на JDK 1.8 все заработало. 
Сейчас пробуем отойти от JDK 11.

**Comment by battleda** [comment]
Переход на JDK 1.8 исправил ситуацию
