### ISSUE TITLE
Ошибка при печати чека, если использовать скидку

### ISSUE THREAD

**Issue by mifkamaz** [shtrih-m/javapos_shtrih#9]
Если печатать чек без скидки
```
            printer.resetPrinter();
            printer.beginFiscalReceipt(true);
            printer.setFiscalReceiptType(FiscalPrinterConst.FPTR_RT_SALES);
            printer.printRecItem("Вода", 10000, 1, 0, 0, "");
            printer.printRecTotal(10000, 10000, "0");
            printer.endFiscalReceipt(true);
```
тогда все ок

Если добавить скидку на поцизию чека
```
            printer.resetPrinter();
            printer.beginFiscalReceipt(true);
            printer.setFiscalReceiptType(FiscalPrinterConst.FPTR_RT_SALES);
            printer.printRecItem("Вода", 10000, 1, 0, 0, "");
            printer.printRecItemAdjustment(FiscalPrinterConst.FPTR_AT_AMOUNT_DISCOUNT, "", 1000, 0);
            printer.printRecTotal(9000, 9000 "0");
            printer.endFiscalReceipt(true);
```
тогда происходит ошибка при вызове метода `endFiscalReceipt`

```
   jpos.JposException: 55, Command is not supported
       at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.getJposExceptionWithoutDetails(JposExceptionHandler.java:84)
       at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.getJposException(JposExceptionHandler.java:52)
       at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.handleException(JposExceptionHandler.java:41)
       at com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl.handleException(FiscalPrinterImpl.java:416)
       at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.handleException(FiscalPrinterService.java:39)
       at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.endFiscalReceipt(FiscalPrinterService.java:1533)
       at jpos.FiscalPrinter.endFiscalReceipt(FiscalPrinter.java:3817)
       at com.shtrih.fiscalprinter.ShtrihFiscalPrinter113.endFiscalReceipt(ShtrihFiscalPrinter113.java:705)
```
Используемое оборудование **ШТРИХ-MOBILE-Ф**

**Comment by nyxiscoo1** [comment]
Это последняя версия драйвера?

P.S. Рекомендую добавить в jpos.xml свойство 
`<prop name="stripExceptionDetails" type="String" value="0"/>`, чтобы получать более полные сообщения об ошибках, из текущего сложно понять в чем дело.

**Comment by mifkamaz** [comment]
Версия драйвера последняя

Установил флаг
Вот стектрейс:
```
jpos.JposException: 55, Command is not supported
             at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.getJposExceptionWithoutDetails(JposExceptionHandler.java:84)
             at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.getJposException(JposExceptionHandler.java:52)
             at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.handleException(JposExceptionHandler.java:41)
             at com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl.handleException(FiscalPrinterImpl.java:416)
             at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.handleException(FiscalPrinterService.java:39)
             at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.endFiscalReceipt(FiscalPrinterService.java:1533)
             at jpos.FiscalPrinter.endFiscalReceipt(FiscalPrinter.java:3817)
             at com.shtrih.fiscalprinter.ShtrihFiscalPrinter113.endFiscalReceipt(ShtrihFiscalPrinter113.java:705)
             at com.bifit.cashdesk.mobile.driver.ShtrihProtocol.<init>(ShtrihProtocol.java:60)
             at com.bifit.cashdesk.mobile.driver.KktDeviceFactory.createConnection(KktDeviceFactory.java:41)
             at com.bifit.cashdesk.mobile.views.tasks.DefaultKkmConnectTask.execute(DefaultKkmConnectTask.java:75)
             at com.bifit.cashdesk.mobile.views.tasks.DefaultKkmConnectTask.execute(DefaultKkmConnectTask.java:21)
             at com.bifit.cashdesk.mobile.views.tasks.AbstractTask$1.run(AbstractTask.java:66)
             at org.greenrobot.eventbus.util.AsyncExecutor$1.run(AsyncExecutor.java:116)
             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
             at java.lang.Thread.run(Thread.java:838)
          Caused by: com.shtrih.fiscalprinter.SmFiscalPrinterException: 55, Command is not supported
             at com.shtrih.fiscalprinter.SMFiscalPrinterImpl.check(SMFiscalPrinterImpl.java:209)
             at com.shtrih.fiscalprinter.SMFiscalPrinterImpl.execute(SMFiscalPrinterImpl.java:214)
             at com.shtrih.fiscalprinter.SMFiscalPrinterImpl.printDiscount(SMFiscalPrinterImpl.java:1017)
             at com.shtrih.jpos.fiscalprinter.receipt.FSSalesReceipt.printFSDiscount(FSSalesReceipt.java:361)
             at com.shtrih.jpos.fiscalprinter.receipt.FSSalesReceipt.printFSSale2(FSSalesReceipt.java:450)
             at com.shtrih.jpos.fiscalprinter.receipt.FSSalesReceipt.printFSSale(FSSalesReceipt.java:390)
             at com.shtrih.jpos.fiscalprinter.receipt.FSSalesReceipt.printReceiptItems(FSSalesReceipt.java:198)
             at com.shtrih.jpos.fiscalprinter.receipt.FSSalesReceipt.endFiscalReceipt(FSSalesReceipt.java:266)
             at com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl.endFiscalReceipt(FiscalPrinterImpl.java:3048)
             at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.endFiscalReceipt(FiscalPrinterService.java:1531)
             at jpos.FiscalPrinter.endFiscalReceipt(FiscalPrinter.java:3817) 
             at com.shtrih.fiscalprinter.ShtrihFiscalPrinter113.endFiscalReceipt(ShtrihFiscalPrinter113.java:705) 
             at com.bifit.cashdesk.mobile.driver.ShtrihProtocol.<init>(ShtrihProtocol.java:60) 
             at com.bifit.cashdesk.mobile.driver.KktDeviceFactory.createConnection(KktDeviceFactory.java:41) 
             at com.bifit.cashdesk.mobile.views.tasks.DefaultKkmConnectTask.execute(DefaultKkmConnectTask.java:75) 
             at com.bifit.cashdesk.mobile.views.tasks.DefaultKkmConnectTask.execute(DefaultKkmConnectTask.java:21) 
             at com.bifit.cashdesk.mobile.views.tasks.AbstractTask$1.run(AbstractTask.java:66) 
             at org.greenrobot.eventbus.util.AsyncExecutor$1.run(AsyncExecutor.java:116) 
             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
             at java.lang.Thread.run(Thread.java:838) 
```

**Comment by nyxiscoo1** [comment]
ШТРИХ-MOBILE-Ф не поддерживает команду скидки, ее расчет это задача ПО которое использует драйвер.

**Comment by Tango600** [comment]
706-й драйвер перестал обрабатывать команду printRecItemAdjustment с параметром adjustmentType = 1. Касса НАНО. Что изменилось?
